---
title: "Getting started with R"
output:
  html_document:
    theme: flatly
    highlight: espresso
    toc: true
    toc_float: true
---
<br/>

##Introduction

<br/>

The first thing to note when writing an article titled *'Getting started with R'* is the abundance of webpages, books and video tutorials already produced, to a very high standard, which provide the relevant details for getting R working on your computer and learning the basics. As I doubt that I could improve upon their efforts, repeating these steps would be pointless exercise for me and the reader, and so I won't bother. 

This may sound quite defeatist, but in actuality it represents a productive ethos when it comes to computer programming; *don't work harder than you need to*. Googling a code problem is much faster than banging your head against a software wall and borrowing a solution is faster than building one. 

This article, then, will have a different focus; initially I cover why I think you should use R. This is far from a unique topic, however it is one for which I can at least offer my own opinion. In the next section I provide links to useful resources online along with some comment on the utility of the types of different R guides available. Then finally, I finish with some basic rules to follow as you begin to learn R programming.

<br/>

##Why use R?

<br/>

If you read Methods in Ecology an Evolution it won't have escaped your notice that every issue has an article roughly titled **'...R a package for...'** *(you can creatively fill in the blanks)*. What does this mean? It means that the authors of the article have developed a set of functions that are available to download through R and which provide an easy way to complete the analysis they have just undertaken. A function being simply a block of code that takes an input (data) and provides an output (graphics, analysis etc.). With this, an extremely fast route to analysis that may have taken weeks and hundreds of lines of code to implement is provided. All that is required from the user is to read the basic instructions for using the functions.

This is the main strength of R. You can take advantage of the efforts and time of other R users and produce cutting edge analysis with relatively little effort and no cost. I could do some machine learning this afternoon and do a PCA tomorrow morning. This pool of packages is also constantly expanding, providing the R user with an ever greater box of tricks. I need only prompt the reader to ponder the comparison of this flexibility with their experience using proprietary software.  

To take advantage of this opportunity though does require a familiarity with the basics of R such that you can understand the functions and use them appropriately. Similarly, it will take some time and effort to get used to reading documentation and asking the right questions from google *(more difficult than you might initially imagine)*. Hopefully though I have provided sufficient reason for this to be a worthwhile effort for the reader *(which it most definitely is)* and so we shall begin the process of getting R onto your computer and beginning to learn the basics.

<br/>

##Getting started with R

<br/>

As I mentioned there are many useful guides already available and ultimately it's of personal preference as to which is most useful. I will however share my experiences with each of the resources. I find books aren't totally necessary but may be helpful early on if one wants to get a better understanding of how R works, an overview of the operations, and advice on how to use R in an efficient way. Videos are initially very helpful but can grow tiresome as the difficulty of the material and the pace with which it is presented are not easily controlled by the viewer. Articles are necessarily limited in scope which is advantageous for focussing on learning a particular new operation but reliance on them can make it difficult for the reader to gain an overview of the language. A combination of these resources and most importantly practice will help the reader quickly develop their skills. 

I would also like to put forward my preference for using RStudio, which is an attractive development environment for using R. This on the whole makes it easier to get started with R and also has features which make coding simpler and faster. Also, download the correct bit version for your machine, it is not initially very important but it can produce some issues later with more advanced programming. 

With these tips in mind follow the below links and get going:

####Websites 
*	Download <a href="https://cran.r-project.org/">R</a>, <a href="https://www.rstudio.com/products/rstudio/">RStudio</a>
*	<a href="https://support.rstudio.com/hc/en-us/articles/201141096-Getting-Started-with-R"> R studio start guide </a>  
* Computer world's	<a href "https://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html?page=2">  start guide </a> 
* Computer world's <a href "https://www.computerworld.com/article/2497464/business-intelligence/business-intelligence-60-r-resources-to-improve-your-data-skills.html">  list of R resources<a/>


####Youtube
*	<a href "https://www.youtube.com/watch?v=cX532N_XLIs"> Video 1</a>
*	<a href "https://www.youtube.com/watch?v=ZoPJGmpYJzw"> Video 2</a> 
*	<a href "https://www.youtube.com/watch?v=MFfRQuQKGYg"> Video 3</a> 

####Books
*	<a href "https://cran.r-project.org/doc/manuals/R-intro.pdf">Introduction to R (free)</a>
*	<a href "https://www.amazon.com/Getting-Started-R-Introduction-Biologists/dp/0198787847/ref=sr_1_1?ie=UTF8&qid=1505662233&sr=8-1&keywords=getting+started+with+r">Getting started with R </a>
* <a href "https://www.amazon.com/R-Dummies-Andrie-Vries/dp/1119055806/ref=sr_1_1?s=books&ie=UTF8&qid=1505662266&sr=1-1&keywords=r+for+dummies">R for Dummies</a>


<br/>

##Rules for R 


<br/>
By this point you should have R and RStudio up and running on your machine and you are no doubt itching to learn some coding. Before you are let loose though I two rules which I think are worth discussing. I have called them rules as on first reading they have the character of friendly advice but experience will show them to be a necessity.

**Only write scripts**. Do not type into the console even when learning the basics. What was learnt will quickly be forgotten and you will find yourself having relook up code you had ran moments earlier. If it is in the script you need only glance up to refresh the memory. Scripts can be saved, recalled, edited, and sent to colleagues; by comparison what goes into the console is gone after you exit that R session.

**Comment scripts**. Hashtags can be used to insert comments into the code. Commentary will make what the code does intelligible to others and to the future versions of yourself who will work on it. It is remarkable how difficult it can be to understand code you have previously written and considerable amounts of time can be wasted working out how it works and what it does. Uncommented code sent to any self-respecting colleague will likely be sent straight back. Life is too short.

<br/>

##Get coding 

<br/>

All that is left now is to start learning the basics using the guides provided. Although these basics are far from thrilling, gaining a good basic understanding forms the necessary platform for all the exciting intermediate and advanced R work that lays in your future. **Good luck and be patient, it's worth it**.