---
title: A<font size="5">LWAYS</font> B<font size="5">E</font> M<font size="5">ODELLING</font>
output:
  html_document:
    theme: flatly
    highlight: espresso
---

<br/>

I believe it is both an exciting and challenging time to be an ecologist! Our knowledge has never been more important as we face a century of human population increase, climate change and environmental degradation. We are also living in an increasingly data rich world; remote sensing, citizen science, mini-sensors and the ubiquitous internet, all provide us with new opportunities to increase our understanding of the natural world.

To make use of this data though we need good tools. Luckily for us there are high quality, flexible, and well-documented tools available and, by the way, the best ones are free. This website will aim to focus on two such tools: <a href="https://www.r-project.org/">R</a> and <a href="https://ccl.northwestern.edu/netlogo/">NetLogo</a>. 

R has become the standard program for statistics in the life sciences and is now exploding with functionality. It can be used for: producing beautiful graphics, machine learning, as a GIS, and even for building websites (like this one). We will be hosting all material from an R club running at the University of Reading called <a href="research.html">pie$R^{2}$</a>, which aims to get students and faculty learning R and sharing their expertise.

NetLogo is a programming language and environment for agent-based modelling. Quantitative prediction has come back into the spotlight in ecology, with the appreciation that the success of our models is the critical test of any understanding. If we predict well it will also allow us to forecast and understand the threats and opportunities in our future. Agent-based models allow us to model the interactions of individuals with their environments mechanistically, providing for more accurate, specific and robust predictions. We have a <a href="https://ibmreading.wordpress.com/">team of agent-based modellers</a> at the University of Reading and we will be hosting material about their modelling experience and research. 



<br/>
<iframe src ="https://lcebutterfly.shinyapps.io/loktavolterra/" width=1000 height=700>

</iframe>

The above interactive plot of the classic <a href="https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations"> Lotka-Volterra</a> equations was produced using RMarkdown and shiny

<br/>

##LATEST pie$R^{2}$ POSTS 
<br/>

<article>
<h3><a href="getting-data-into-R.html">GETTING DATA INTO R</a></h3>
<div class="summary">
<span><i class="fa fa-calendar"></i> _2017-09-24_</span>
<p> 
##Introduction

Successfully getting your dataset into R is like whistling; once you know how it's hard to imagine finding it difficult, yet presumably at some point it was. It's not my intention to trivialise any possible frustration... </p>
<a href="getting-data-into-R.html">Full Post</a>
</div>
</article>

<br/>

<article>
<h3><a href="getting-started-with-R.html">GETTING STARTED WITH R</a></h3>
<div class="summary">
<span><i class="fa fa-calendar"></i> _2017-09-17_</span>
<p> 
##Introduction

The first thing to note when writing an article titled *'Getting started with R'* is the abundance of webpages, books and video tutorials already produced, to a very high standard, which provide the relevant details for getting R working on your computer... </p>
<a href="getting-started-with-R.html">Full Post</a>
</div>
</article>




<br/>

## BLOG POSTS

